# This file was generated by GoReleaser. DO NOT EDIT.
class Antibody < Formula
  desc "The fastest shell plugin manager"
  homepage "http://getantibody.github.io"
  version "4.1.2"

  if OS.mac?
    url "https://github.com/getantibody/antibody/releases/download/v4.1.2/antibody_Darwin_x86_64.tar.gz"
    sha256 "d84cd6776177c2bc1581d3a0fc88c6c156a50eebda8be19739d6a7aa2793ba35"
  elsif OS.linux?
    url "https://github.com/getantibody/antibody/releases/download/v4.1.2/antibody_Linux_x86_64.tar.gz"
    sha256 "1653956d82dfc4a57a417205dbea65074a012d1ba038aca6f5f34db8af993b78"
  end
  
  depends_on "git"

  def install
    bin.install "antibody"
  end

  def caveats; <<~EOS
    To start using antibody, you need to add `source <(antibody init)` to your `~/.zshrc`.
  EOS
  end
end
