# This file was generated by GoReleaser. DO NOT EDIT.
class Antibody < Formula
  desc "The fastest shell plugin manager"
  homepage "http://getantibody.github.io"
  version "5.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/getantibody/antibody/releases/download/v5.0.0/antibody_Darwin_x86_64.tar.gz"
    sha256 "b2c828178333c619b2435905564fd0cd78d1537bf781fe3f50400c7e87f720f1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/getantibody/antibody/releases/download/v5.0.0/antibody_Linux_x86_64.tar.gz"
      sha256 "8a8dbc889fa4a7bcb5a942e8abe5fde9c6ff266b8bfdccec035f492392796b0c"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getantibody/antibody/releases/download/v5.0.0/antibody_Linux_arm64.tar.gz"
        sha256 "86a56bbd541f837712f5db34412bd7d20bcabbe366bccfd532647a7d4eb1fda5"
      else
        url "https://github.com/getantibody/antibody/releases/download/v5.0.0/antibody_Linux_armv6.tar.gz"
        sha256 "f6d96b8fc713307bb50a2c9d15734a3890eca16fa4ad4df3397b7cfc3b8c5322"
      end
    end
  end

  def install
    bin.install "antibody"
  end

  def caveats; <<~EOS
    To start using antibody, you need to add `source <(antibody init)` to your `~/.zshrc`.
  EOS
  end
end
