# This file was generated by GoReleaser. DO NOT EDIT.
class Antibody < Formula
  desc "The fastest shell plugin manager"
  homepage "http://getantibody.github.io"
  url "https://github.com/getantibody/antibody/releases/download/v4.1.1/antibody_Darwin_x86_64.tar.gz"
  version "4.1.1"
  sha256 "b5eed7230ff337289772463b054b9bc13d2dafaa8fb4a1eb9629656f84844016"
  
  depends_on "git"

  def install
    bin.install "antibody"
  end

  def caveats; <<~EOS
    To start using antibody, you need to add `source <(antibody init)` to your `~/.zshrc`.
  EOS
  end
end
